// ─────────────────────────────────────────────────────────────────────────────
// PrismRx — Mock data for demo
// Realistic Policy DNA objects for autoimmune/inflammatory infused biologics.
// All data is synthetic and derived from public payer policy document patterns.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  PolicyDNA,
  CoverageMatrixData,
  MatrixRow,
  MatrixCell,
  DrugFamily,
  PolicyDiff,
} from './types'

// ── Drug families ─────────────────────────────────────────────────────────────

export const DRUG_FAMILIES: DrugFamily[] = [
  {
    key: 'infliximab',
    display_name: 'Infliximab',
    short_name: 'IFX',
    reference_product: 'Remicade',
    biosimilars: ['Inflectra', 'Renflexis', 'Avsola'],
    mechanism: 'TNF-α inhibitor',
    indications: ['Rheumatoid Arthritis', 'Crohn\'s Disease', 'Ulcerative Colitis', 'Psoriatic Arthritis', 'Ankylosing Spondylitis'],
    hcpcs_codes: ['J1745', 'Q5102', 'Q5103', 'Q5121'],
  },
  {
    key: 'rituximab',
    display_name: 'Rituximab',
    short_name: 'RTX',
    reference_product: 'Rituxan',
    biosimilars: ['Truxima', 'Ruxience', 'Riabni'],
    mechanism: 'Anti-CD20 monoclonal antibody',
    indications: ['Rheumatoid Arthritis', 'Granulomatosis with Polyangiitis', 'Microscopic Polyangiitis'],
    hcpcs_codes: ['J9312', 'Q5115', 'Q5119', 'Q5123'],
  },
  {
    key: 'vedolizumab',
    display_name: 'Vedolizumab',
    short_name: 'VDZ',
    reference_product: 'Entyvio',
    biosimilars: [],
    mechanism: 'Anti-α4β7 integrin',
    indications: ['Ulcerative Colitis', 'Crohn\'s Disease'],
    hcpcs_codes: ['J3380'],
  },
  {
    key: 'tocilizumab_iv',
    display_name: 'Tocilizumab IV',
    short_name: 'TCZ',
    reference_product: 'Actemra',
    biosimilars: ['Tyenne'],
    mechanism: 'Anti-IL-6 receptor',
    indications: ['Rheumatoid Arthritis', 'Giant Cell Arteritis', 'Systemic Juvenile Idiopathic Arthritis', 'Cytokine Release Syndrome'],
    hcpcs_codes: ['J3262', 'Q5127'],
  },
  {
    key: 'ocrelizumab',
    display_name: 'Ocrelizumab',
    short_name: 'OCR',
    reference_product: 'Ocrevus',
    biosimilars: [],
    mechanism: 'Anti-CD20 monoclonal antibody',
    indications: ['Relapsing-Remitting MS', 'Primary Progressive MS'],
    hcpcs_codes: ['J2350'],
  },
]

// ── Payer definitions ─────────────────────────────────────────────────────────

export const PAYERS = {
  aetna:  'Aetna',
  uhc:    'UnitedHealthcare',
  bsca:   'Blue Shield CA',
  anthem: 'Anthem',
  cigna:  'Cigna',
}

export const PAYER_IDS = Object.keys(PAYERS) as Array<keyof typeof PAYERS>

// ── Policy DNA objects ────────────────────────────────────────────────────────
// 25 records: 5 drugs × 5 payers

export const MOCK_POLICIES: PolicyDNA[] = [

  // ── INFLIXIMAB ──────────────────────────────────────────────────────────────

  {
    id: 'pol_ifx_aetna_q42024',
    canonical_drug_key: 'infliximab',
    drug_display_name: 'Infliximab',
    drug_short_name: 'IFX',
    biosimilars: ['Inflectra', 'Renflexis', 'Avsola'],
    reference_product: 'Remicade',
    hcpcs_codes: ['J1745', 'Q5102', 'Q5103', 'Q5121'],
    payer_id: 'aetna',
    payer_name: 'Aetna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'a3f7e2b1c9d4f5a8',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate (≥3 months)', 'one additional csDMARD'],
      diagnosis_required: ['Rheumatoid Arthritis (seropositive)', 'Psoriatic Arthritis', 'Ankylosing Spondylitis', 'Crohn\'s Disease', 'Ulcerative Colitis'],
      specialty_required: 'Rheumatologist or Gastroenterologist',
      lab_requirements: ['Negative TB test (QuantiFERON or TST)', 'Baseline LFTs within 3 months'],
      age_restriction: null,
      additional_notes: ['Biosimilar preferred over reference product Remicade', 'Remicade requires non-medical exception if biosimilar appropriate'],
    },
    operational_rules: {
      site_of_care: 'Outpatient infusion center or physician office; hospital outpatient requires medical exception',
      renewal_interval_days: 180,
      dosing_notes: 'Initial: 3–5 mg/kg IV. Maintenance: 3–5 mg/kg IV at weeks 2, 6, then every 8 weeks.',
      documentation_required: ['PA form', 'Prescriber specialty attestation', 'TB test result', 'Failed therapy documentation'],
      quantity_limit: '5 mg/kg; max 10 vials per infusion per site-of-care policy',
    },
    evidence_citations: [
      {
        id: 'cite_ifx_aetna_1',
        page: 3,
        section: '2.1 Coverage Criteria',
        quote: 'Coverage for infliximab and its biosimilars requires documentation of adequate trial and failure of at least two conventional synthetic DMARDs, including methotrexate for a minimum duration of three months unless contraindicated.',
        source_label: 'Aetna Clinical Policy Bulletin: Infliximab (CPB #0208)',
        source_url: 'https://www.aetna.com/cpb/medical/data/200_299/0208.html',
        effective_date: '2024-10-01',
      },
      {
        id: 'cite_ifx_aetna_2',
        page: 5,
        section: '2.3 Site of Care',
        quote: 'Infusion of infliximab in a hospital outpatient setting requires prior authorization and demonstration that lower-cost settings are not medically appropriate.',
        source_label: 'Aetna Clinical Policy Bulletin: Infliximab (CPB #0208)',
        source_url: 'https://www.aetna.com/cpb/medical/data/200_299/0208.html',
        effective_date: '2024-10-01',
      },
      {
        id: 'cite_ifx_aetna_3',
        page: 7,
        section: '3.1 Biosimilar Preference',
        quote: 'Remicade (reference infliximab) is non-preferred. An FDA-approved biosimilar (Inflectra, Renflexis, or Avsola) must be used unless a non-medical exception is submitted and approved.',
        source_label: 'Aetna Clinical Policy Bulletin: Infliximab (CPB #0208)',
        source_url: 'https://www.aetna.com/cpb/medical/data/200_299/0208.html',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 72,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: true,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_ifx_uhc_q42024',
    canonical_drug_key: 'infliximab',
    drug_display_name: 'Infliximab',
    drug_short_name: 'IFX',
    biosimilars: ['Inflectra', 'Renflexis', 'Avsola'],
    reference_product: 'Remicade',
    hcpcs_codes: ['J1745', 'Q5102', 'Q5103', 'Q5121'],
    payer_id: 'uhc',
    payer_name: 'UnitedHealthcare',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'b2d8a1e7c3f4b6d9',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate (≥3 months)'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Psoriatic Arthritis', 'Ankylosing Spondylitis', 'Crohn\'s Disease', 'Ulcerative Colitis', 'Plaque Psoriasis'],
      specialty_required: 'Rheumatologist, Gastroenterologist, or Dermatologist per indication',
      lab_requirements: ['Negative TB screening', 'CBC within 6 months'],
      age_restriction: null,
      additional_notes: ['UHC Biosimilar Initiative: FDA-approved biosimilar required'],
    },
    operational_rules: {
      site_of_care: 'Provider-administered in approved infusion site; home infusion not covered for initial doses',
      renewal_interval_days: 180,
      dosing_notes: 'Per FDA label; dose escalation to 10 mg/kg requires separate review.',
      documentation_required: ['PA form', 'Specialty confirmation', 'TB screening', 'CDAI or DAS28 score for renewal'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ifx_uhc_1',
        page: 2,
        section: 'Coverage Criteria — Rheumatoid Arthritis',
        quote: 'Prior authorization is required. Patient must have an inadequate response to methotrexate of at least 3 months duration. FDA-approved biosimilar infliximab must be used per UHC Biosimilar Initiative policy.',
        source_label: 'UHC Medical Drug Policy: Tumor Necrosis Factor (TNF) Inhibitors (D0010)',
        source_url: 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/drug/tnf-inhibitors.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 65,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_ifx_bsca_q42024',
    canonical_drug_key: 'infliximab',
    drug_display_name: 'Infliximab',
    drug_short_name: 'IFX',
    biosimilars: ['Inflectra', 'Renflexis', 'Avsola'],
    reference_product: 'Remicade',
    hcpcs_codes: ['J1745', 'Q5102', 'Q5103', 'Q5121'],
    payer_id: 'bsca',
    payer_name: 'Blue Shield CA',
    plan_type: 'Commercial',
    effective_date: '2025-01-01',
    version_label: 'Q1 2025',
    document_hash: 'c1e9b3d7f2a4c8e1',
    coverage_status: 'preferred',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['one csDMARD for RA; no step required for IBD if moderate-severe'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Crohn\'s Disease', 'Ulcerative Colitis', 'Psoriatic Arthritis'],
      specialty_required: 'Rheumatologist or Gastroenterologist',
      lab_requirements: ['TB test (IGRA preferred)', 'Hepatitis B surface antigen'],
      age_restriction: null,
      additional_notes: ['Biosimilar (Inflectra, Renflexis, Avsola) is preferred tier. Remicade covered only with medical exception demonstrating clinical distinction.'],
    },
    operational_rules: {
      site_of_care: 'Outpatient infusion center preferred; home infusion allowed for stable patients after ≥3 uneventful infusions',
      renewal_interval_days: 365,
      dosing_notes: 'Standard dosing per label. Dose escalation reviewed at renewal.',
      documentation_required: ['PA form', 'TB test', 'HBsAg result', 'Prescriber attestation'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ifx_bsca_1',
        page: 4,
        section: 'Preferred Agents',
        quote: 'Infliximab biosimilars (Inflectra, Renflexis, Avsola) are the preferred agents within the infliximab drug class. Remicade is covered only with an approved non-medical exception.',
        source_label: 'Blue Shield CA Medical Drug Criteria: Infliximab (Policy CG-MED-142)',
        source_url: 'https://www.blueshieldca.com/bsca/bsc/wcm/connect/provider/provider_content_en/guidelines_resources/medical_drug_criteria/infliximab',
        effective_date: '2025-01-01',
      },
    ],
    friction_score: 48,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_ifx_anthem_q42024',
    canonical_drug_key: 'infliximab',
    drug_display_name: 'Infliximab',
    drug_short_name: 'IFX',
    biosimilars: ['Inflectra', 'Renflexis', 'Avsola'],
    reference_product: 'Remicade',
    hcpcs_codes: ['J1745', 'Q5102', 'Q5103', 'Q5121'],
    payer_id: 'anthem',
    payer_name: 'Anthem',
    plan_type: 'Commercial',
    effective_date: '2024-07-01',
    version_label: 'Q3 2024',
    document_hash: 'd4f6c2a8b1e3d7f9',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate (≥12 weeks)', 'one additional DMARD for RA'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Crohn\'s Disease', 'Ulcerative Colitis', 'Ankylosing Spondylitis', 'Psoriatic Arthritis'],
      specialty_required: 'Specialist required per indication',
      lab_requirements: ['TB test', 'Liver function tests'],
      age_restriction: 'Pediatric Crohn\'s: age ≥6',
      additional_notes: ['Biosimilar preferred; Remicade requires clinical justification'],
    },
    operational_rules: {
      site_of_care: 'Hospital outpatient requires non-medical necessity exception; approved sites include physician office, infusion center',
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Lab results', 'Treatment failure documentation'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ifx_anthem_1',
        page: 3,
        section: 'Initial Criteria — Rheumatoid Arthritis',
        quote: 'Coverage requires prior trial and failure of methotrexate for minimum 12 weeks and at least one additional conventional DMARD, unless contraindicated.',
        source_label: 'Anthem Medical Policy: Infliximab and Biosimilars (MED.00100)',
        source_url: 'https://www.anthem.com/dam/medpolicies/abcbs/active/policies/mp_pw_a051620.html',
        effective_date: '2024-07-01',
      },
    ],
    friction_score: 70,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: true,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_ifx_cigna_q42024',
    canonical_drug_key: 'infliximab',
    drug_display_name: 'Infliximab',
    drug_short_name: 'IFX',
    biosimilars: ['Inflectra', 'Renflexis', 'Avsola'],
    reference_product: 'Remicade',
    hcpcs_codes: ['J1745', 'Q5102', 'Q5103', 'Q5121'],
    payer_id: 'cigna',
    payer_name: 'Cigna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'e5b7d1c3a9f2e6b8',
    coverage_status: 'nonpreferred',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate (≥3 months)', 'one additional csDMARD', 'FDA-approved biosimilar must be tried first for originator'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Crohn\'s Disease', 'Ulcerative Colitis', 'Psoriatic Arthritis', 'Ankylosing Spondylitis'],
      specialty_required: 'Rheumatologist or Gastroenterologist',
      lab_requirements: ['Negative TB test', 'CBC', 'LFTs'],
      age_restriction: null,
      additional_notes: ['Remicade (originator) is non-preferred. Biosimilar must be tried first. Originator covered only with documented biosimilar failure or contraindication.'],
    },
    operational_rules: {
      site_of_care: 'Restricted to non-hospital settings; hospital outpatient denied without site-of-care exception',
      renewal_interval_days: 180,
      dosing_notes: 'Originator dose-escalation (>5 mg/kg) requires separate PA.',
      documentation_required: ['PA form', 'Biosimilar trial documentation or contraindication', 'TB test', 'Labs'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ifx_cigna_1',
        page: 2,
        section: 'Coverage Conditions — Step Therapy',
        quote: 'For members seeking coverage of reference infliximab (Remicade), documentation of an adequate trial and failure of an FDA-approved biosimilar infliximab product is required, unless a documented contraindication exists.',
        source_label: 'Cigna Coverage Policy: Infliximab and Biosimilars (MMR1005)',
        source_url: 'https://www.cigna.com/static/www-cigna-com/docs/health-care-professionals/coverage-policies/ph_1005_coveragepositioncriteria_infliximab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 82,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: true,
      renewal_complexity: true,
    },
  },

  // ── RITUXIMAB ───────────────────────────────────────────────────────────────

  {
    id: 'pol_rtx_aetna_q42024',
    canonical_drug_key: 'rituximab',
    drug_display_name: 'Rituximab',
    drug_short_name: 'RTX',
    biosimilars: ['Truxima', 'Ruxience', 'Riabni'],
    reference_product: 'Rituxan',
    hcpcs_codes: ['J9312', 'Q5115', 'Q5119', 'Q5123'],
    payer_id: 'aetna',
    payer_name: 'Aetna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'f6a8e4c2d1b7f3a9',
    coverage_status: 'covered',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['Rheumatoid Arthritis (inadequate response to anti-TNF)', 'Granulomatosis with Polyangiitis', 'Microscopic Polyangiitis'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['Hepatitis B screen (HBsAg, anti-HBc)', 'CBC within 3 months'],
      age_restriction: null,
      additional_notes: ['For RA: requires documented failure of at least one anti-TNF agent. For GPA/MPA: rituximab is first-line.'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: 'RA: 1000 mg IV × 2 doses separated by 2 weeks. Repeat courses every 24 weeks or upon return of disease activity. GPA/MPA: 375 mg/m² weekly × 4.',
      documentation_required: ['PA form', 'Anti-TNF failure documentation (for RA)', 'HBV screen results'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_rtx_aetna_1',
        page: 4,
        section: '2.2 Rheumatoid Arthritis Criteria',
        quote: 'Rituximab is covered for adult patients with moderate-to-severe RA who have had an inadequate response to one or more anti-TNF agents.',
        source_label: 'Aetna Clinical Policy Bulletin: Rituximab (CPB #0436)',
        source_url: 'https://www.aetna.com/cpb/medical/data/400_499/0436.html',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 42,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_rtx_uhc_q42024',
    canonical_drug_key: 'rituximab',
    drug_display_name: 'Rituximab',
    drug_short_name: 'RTX',
    biosimilars: ['Truxima', 'Ruxience', 'Riabni'],
    reference_product: 'Rituxan',
    hcpcs_codes: ['J9312', 'Q5115', 'Q5119', 'Q5123'],
    payer_id: 'uhc',
    payer_name: 'UnitedHealthcare',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'a1c3e5b7d9f2a4c6',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: ['one anti-TNF for RA indication'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Granulomatosis with Polyangiitis', 'Microscopic Polyangiitis'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['HBsAg', 'anti-HBc', 'CBC'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Anti-TNF failure', 'HBV labs'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_rtx_uhc_1',
        page: 3,
        section: 'RA Indication',
        quote: 'Authorization requires prior inadequate response to an anti-TNF biologic in RA. Biosimilar must be used per UHC Biosimilar Initiative.',
        source_label: 'UHC Medical Drug Policy: Rituximab (D0035)',
        source_url: 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/drug/rituximab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 55,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_rtx_bsca_q12025',
    canonical_drug_key: 'rituximab',
    drug_display_name: 'Rituximab',
    drug_short_name: 'RTX',
    biosimilars: ['Truxima', 'Ruxience', 'Riabni'],
    reference_product: 'Rituxan',
    hcpcs_codes: ['J9312', 'Q5115', 'Q5119', 'Q5123'],
    payer_id: 'bsca',
    payer_name: 'Blue Shield CA',
    plan_type: 'Commercial',
    effective_date: '2025-01-01',
    version_label: 'Q1 2025',
    document_hash: 'b2d4f6a8c1e3b5d7',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: ['anti-TNF failure for RA'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Granulomatosis with Polyangiitis', 'Microscopic Polyangiitis'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['HBV screening', 'CBC'],
      age_restriction: null,
      additional_notes: ['Biosimilar preferred; Rituxan non-medical exception required'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: null,
      documentation_required: ['PA form', 'Anti-TNF trial', 'HBV results'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_rtx_bsca_1',
        page: 2,
        section: 'Criteria Summary',
        quote: 'Rituximab biosimilars are the preferred agents. Rituxan (originator) requires a non-medical exception with clinical justification.',
        source_label: 'Blue Shield CA Medical Drug Criteria: Rituximab (Policy CG-MED-198)',
        source_url: 'https://www.blueshieldca.com/bsca/bsc/wcm/connect/provider/provider_content_en/guidelines_resources/medical_drug_criteria/rituximab',
        effective_date: '2025-01-01',
      },
    ],
    friction_score: 52,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_rtx_anthem_q32024',
    canonical_drug_key: 'rituximab',
    drug_display_name: 'Rituximab',
    drug_short_name: 'RTX',
    biosimilars: ['Truxima', 'Ruxience', 'Riabni'],
    reference_product: 'Rituxan',
    hcpcs_codes: ['J9312', 'Q5115', 'Q5119', 'Q5123'],
    payer_id: 'anthem',
    payer_name: 'Anthem',
    plan_type: 'Commercial',
    effective_date: '2024-07-01',
    version_label: 'Q3 2024',
    document_hash: 'c3e5b7d9a1f4c6e8',
    coverage_status: 'covered',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['Rheumatoid Arthritis', 'GPA', 'MPA'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['HBsAg', 'CBC'],
      age_restriction: null,
      additional_notes: ['RA: requires anti-TNF inadequate response. GPA/MPA: first-line acceptable.'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'HBV screen'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_rtx_anthem_1',
        page: 3,
        section: 'Indications — RA',
        quote: 'Rituximab is medically necessary for members with RA who have had an inadequate response to anti-TNF biologics.',
        source_label: 'Anthem Medical Policy: Rituximab (MED.00088)',
        source_url: 'https://www.anthem.com/dam/medpolicies/abcbs/active/policies/mp_pw_b051621.html',
        effective_date: '2024-07-01',
      },
    ],
    friction_score: 40,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_rtx_cigna_q42024',
    canonical_drug_key: 'rituximab',
    drug_display_name: 'Rituximab',
    drug_short_name: 'RTX',
    biosimilars: ['Truxima', 'Ruxience', 'Riabni'],
    reference_product: 'Rituxan',
    hcpcs_codes: ['J9312', 'Q5115', 'Q5119', 'Q5123'],
    payer_id: 'cigna',
    payer_name: 'Cigna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'd4f8b2c6a0e7d1f3',
    coverage_status: 'covered',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: ['anti-TNF failure (RA)'],
      diagnosis_required: ['Rheumatoid Arthritis', 'GPA', 'MPA'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['HBsAg', 'anti-HBc total'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'HBV labs', 'Anti-TNF failure docs'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_rtx_cigna_1',
        page: 3,
        section: 'RA Coverage Conditions',
        quote: 'Rituximab is covered for moderate-to-severe RA with documented failure of anti-TNF therapy. Biosimilar rituximab products are considered therapeutically equivalent.',
        source_label: 'Cigna Coverage Policy: Rituximab (MMR1012)',
        source_url: 'https://www.cigna.com/static/www-cigna-com/docs/health-care-professionals/coverage-policies/ph_1012_coveragepositioncriteria_rituximab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 38,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  // ── VEDOLIZUMAB ─────────────────────────────────────────────────────────────

  {
    id: 'pol_vdz_aetna_q42024',
    canonical_drug_key: 'vedolizumab',
    drug_display_name: 'Vedolizumab',
    drug_short_name: 'VDZ',
    biosimilars: [],
    reference_product: 'Entyvio',
    hcpcs_codes: ['J3380'],
    payer_id: 'aetna',
    payer_name: 'Aetna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'e5a7c9b1d3f6e2a8',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['corticosteroids (≥3 months)', 'immunomodulator (azathioprine or 6-MP for ≥3 months)', 'anti-TNF (≥3 months) or contraindicated'],
      diagnosis_required: ['Ulcerative Colitis (moderate-severe)', 'Crohn\'s Disease (moderate-severe)'],
      specialty_required: 'Gastroenterologist',
      lab_requirements: ['TB test', 'Baseline CBC', 'CRP or endoscopic evidence of activity'],
      age_restriction: null,
      additional_notes: ['Can be first-line biologic if anti-TNF is contraindicated.'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: 'UC & CD: 300 mg IV at weeks 0, 2, 6, then every 8 weeks.',
      documentation_required: ['PA form', 'GI specialist notes', 'Endoscopy or imaging report', 'Step therapy documentation'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_vdz_aetna_1',
        page: 3,
        section: '2.1 UC/CD Criteria',
        quote: 'Vedolizumab requires documented failure of a corticosteroid, immunomodulator, and anti-TNF prior to authorization, unless anti-TNF is contraindicated.',
        source_label: 'Aetna Clinical Policy Bulletin: Vedolizumab (CPB #0886)',
        source_url: 'https://www.aetna.com/cpb/medical/data/800_899/0886.html',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 68,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_vdz_uhc_q42024',
    canonical_drug_key: 'vedolizumab',
    drug_display_name: 'Vedolizumab',
    drug_short_name: 'VDZ',
    biosimilars: [],
    reference_product: 'Entyvio',
    hcpcs_codes: ['J3380'],
    payer_id: 'uhc',
    payer_name: 'UnitedHealthcare',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'f6b8d0c2e4a7f1b3',
    coverage_status: 'covered',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: ['conventional therapy (corticosteroid or immunomodulator)'],
      diagnosis_required: ['Ulcerative Colitis (moderate-severe)', 'Crohn\'s Disease (moderate-severe)'],
      specialty_required: 'Gastroenterologist',
      lab_requirements: ['TB screening'],
      age_restriction: null,
      additional_notes: ['No anti-TNF step required; vedolizumab may be used as first biologic.'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: null,
      documentation_required: ['PA form', 'Diagnosis documentation', 'Conventional therapy trial'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_vdz_uhc_1',
        page: 2,
        section: 'Authorization Criteria',
        quote: 'Vedolizumab (Entyvio) is covered for moderate-to-severe UC or CD following conventional therapy. Anti-TNF step therapy is not required.',
        source_label: 'UHC Medical Drug Policy: Vedolizumab (D0072)',
        source_url: 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/drug/vedolizumab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 32,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: false,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_vdz_bsca_q12025',
    canonical_drug_key: 'vedolizumab',
    drug_display_name: 'Vedolizumab',
    drug_short_name: 'VDZ',
    biosimilars: [],
    reference_product: 'Entyvio',
    hcpcs_codes: ['J3380'],
    payer_id: 'bsca',
    payer_name: 'Blue Shield CA',
    plan_type: 'Commercial',
    effective_date: '2025-01-01',
    version_label: 'Q1 2025',
    document_hash: 'a9c1e3b5d7f0a2c4',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['corticosteroid', 'immunomodulator', 'anti-TNF unless contraindicated'],
      diagnosis_required: ['Ulcerative Colitis (moderate-severe)', 'Crohn\'s Disease (moderate-severe)'],
      specialty_required: 'Gastroenterologist',
      lab_requirements: ['TB test', 'Baseline LFTs'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: null,
      documentation_required: ['PA form', 'Step therapy documentation', 'GI specialist notes'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_vdz_bsca_1',
        page: 3,
        section: 'Coverage Criteria',
        quote: 'Prior authorization required. Three-step prior therapy required: conventional therapy, immunomodulator, and anti-TNF unless anti-TNF contraindicated.',
        source_label: 'Blue Shield CA Medical Drug Criteria: Vedolizumab (Policy CG-MED-214)',
        source_url: 'https://www.blueshieldca.com/bsca/bsc/wcm/connect/provider/provider_content_en/guidelines_resources/medical_drug_criteria/vedolizumab',
        effective_date: '2025-01-01',
      },
    ],
    friction_score: 62,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_vdz_anthem_q32024',
    canonical_drug_key: 'vedolizumab',
    drug_display_name: 'Vedolizumab',
    drug_short_name: 'VDZ',
    biosimilars: [],
    reference_product: 'Entyvio',
    hcpcs_codes: ['J3380'],
    payer_id: 'anthem',
    payer_name: 'Anthem',
    plan_type: 'Commercial',
    effective_date: '2024-07-01',
    version_label: 'Q3 2024',
    document_hash: 'b0d2f4a6c8e1b3d5',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['corticosteroid', 'immunomodulator'],
      diagnosis_required: ['Moderate-to-severe UC', 'Moderate-to-severe CD'],
      specialty_required: 'Gastroenterologist',
      lab_requirements: ['TB test'],
      age_restriction: null,
      additional_notes: ['No mandatory anti-TNF step for vedolizumab'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: null,
      documentation_required: ['PA form', 'Specialist notes'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_vdz_anthem_1',
        page: 4,
        section: 'Criteria — UC/CD',
        quote: 'Vedolizumab is covered following failure of conventional therapy. Anti-TNF step not required.',
        source_label: 'Anthem Medical Policy: Vedolizumab (MED.00125)',
        source_url: 'https://www.anthem.com/dam/medpolicies/abcbs/active/policies/mp_pw_c051622.html',
        effective_date: '2024-07-01',
      },
    ],
    friction_score: 55,
    friction_factors: {
      prior_failure_count: 1,
      specialist_gate: true,
      lab_biomarker_gate: false,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_vdz_cigna_q42024',
    canonical_drug_key: 'vedolizumab',
    drug_display_name: 'Vedolizumab',
    drug_short_name: 'VDZ',
    biosimilars: [],
    reference_product: 'Entyvio',
    hcpcs_codes: ['J3380'],
    payer_id: 'cigna',
    payer_name: 'Cigna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'c1e3a5b7d9f2c4e6',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['corticosteroid', 'immunomodulator', 'anti-TNF'],
      diagnosis_required: ['UC (moderate-severe)', 'CD (moderate-severe)'],
      specialty_required: 'Gastroenterologist',
      lab_requirements: ['TB screening'],
      age_restriction: null,
      additional_notes: ['Anti-TNF mandatory step unless contraindicated or intolerant'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: null,
      documentation_required: ['PA form', 'Step therapy docs', 'GI records'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_vdz_cigna_1',
        page: 3,
        section: 'Authorization Requirements',
        quote: 'Vedolizumab requires prior failure of conventional therapy and an anti-TNF biologic. Anti-TNF trial is mandatory unless there is a documented contraindication.',
        source_label: 'Cigna Coverage Policy: Vedolizumab (MMR1018)',
        source_url: 'https://www.cigna.com/static/www-cigna-com/docs/health-care-professionals/coverage-policies/ph_1018_coveragepositioncriteria_vedolizumab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 60,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: false,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  // ── TOCILIZUMAB IV ──────────────────────────────────────────────────────────

  {
    id: 'pol_tcz_aetna_q42024',
    canonical_drug_key: 'tocilizumab_iv',
    drug_display_name: 'Tocilizumab IV',
    drug_short_name: 'TCZ',
    biosimilars: ['Tyenne'],
    reference_product: 'Actemra',
    hcpcs_codes: ['J3262', 'Q5127'],
    payer_id: 'aetna',
    payer_name: 'Aetna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'd2f4b6a8c0e3d7f1',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate (≥3 months)', 'one anti-TNF'],
      diagnosis_required: ['Rheumatoid Arthritis', 'Giant Cell Arteritis', 'sJIA', 'pJIA'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['Lipid panel', 'CBC', 'LFTs', 'TB test'],
      age_restriction: 'pJIA: age ≥2; sJIA: age ≥2',
      additional_notes: ['GCA: tocilizumab IV may be first-line. RA: requires prior DMARD and anti-TNF failure.'],
    },
    operational_rules: {
      site_of_care: 'Intravenous formulation: approved infusion site only; SC formulation preferred for home use',
      renewal_interval_days: 180,
      dosing_notes: 'RA: 4–8 mg/kg IV every 4 weeks.',
      documentation_required: ['PA form', 'Lipid panel', 'CBC', 'LFTs', 'TB test', 'Specialist attestation'],
      quantity_limit: 'IV: 8 mg/kg max; dose-escalation review required',
    },
    evidence_citations: [
      {
        id: 'cite_tcz_aetna_1',
        page: 4,
        section: '2.1 RA Criteria',
        quote: 'Tocilizumab IV requires prior failure of methotrexate and an anti-TNF biologic. Baseline lipid panel and CBC required before initiation.',
        source_label: 'Aetna Clinical Policy Bulletin: Tocilizumab (CPB #0655)',
        source_url: 'https://www.aetna.com/cpb/medical/data/600_699/0655.html',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 73,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: true,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_tcz_uhc_q42024',
    canonical_drug_key: 'tocilizumab_iv',
    drug_display_name: 'Tocilizumab IV',
    drug_short_name: 'TCZ',
    biosimilars: ['Tyenne'],
    reference_product: 'Actemra',
    hcpcs_codes: ['J3262', 'Q5127'],
    payer_id: 'uhc',
    payer_name: 'UnitedHealthcare',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'e3a5c7b9d1f4e6a8',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate (≥3 months)', 'one anti-TNF'],
      diagnosis_required: ['Rheumatoid Arthritis', 'GCA'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['Lipid panel', 'CBC', 'LFTs'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Labs', 'Step therapy documentation'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_tcz_uhc_1',
        page: 3,
        section: 'RA — Step Therapy',
        quote: 'Tocilizumab IV requires prior failure of methotrexate and one anti-TNF before authorization.',
        source_label: 'UHC Medical Drug Policy: Tocilizumab (D0062)',
        source_url: 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/drug/tocilizumab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 65,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_tcz_bsca_q12025',
    canonical_drug_key: 'tocilizumab_iv',
    drug_display_name: 'Tocilizumab IV',
    drug_short_name: 'TCZ',
    biosimilars: ['Tyenne'],
    reference_product: 'Actemra',
    hcpcs_codes: ['J3262', 'Q5127'],
    payer_id: 'bsca',
    payer_name: 'Blue Shield CA',
    plan_type: 'Commercial',
    effective_date: '2025-01-01',
    version_label: 'Q1 2025',
    document_hash: 'f4b6d8e0c2a5f7b9',
    coverage_status: 'not_covered',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate', 'two DMARDs', 'two anti-TNF agents'],
      diagnosis_required: ['Rheumatoid Arthritis'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['Lipid panel', 'CBC', 'LFTs', 'TB test'],
      age_restriction: null,
      additional_notes: [
        'IV formulation is NOT covered as first-choice route. Subcutaneous formulation must be used unless medically contraindicated.',
        'Hospital outpatient infusion for tocilizumab IV is denied without site-of-care exception.',
      ],
    },
    operational_rules: {
      site_of_care: 'Hospital outpatient: NOT covered. Physician office or approved infusion center only. SC formulation preferred.',
      renewal_interval_days: 180,
      dosing_notes: 'IV to SC switch encouraged at renewal.',
      documentation_required: ['PA form', 'SC contraindication documentation', 'Site-of-care justification', 'Labs', 'Step therapy'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_tcz_bsca_1',
        page: 6,
        section: 'Route of Administration — IV vs SC',
        quote: 'Tocilizumab IV is not covered when the subcutaneous formulation is clinically appropriate. Coverage for IV requires documented contraindication to SC administration and prior failure of two anti-TNF agents.',
        source_label: 'Blue Shield CA Medical Drug Criteria: Tocilizumab (Policy CG-MED-178)',
        source_url: 'https://www.blueshieldca.com/bsca/bsc/wcm/connect/provider/provider_content_en/guidelines_resources/medical_drug_criteria/tocilizumab',
        effective_date: '2025-01-01',
      },
    ],
    friction_score: 91,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: true,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_tcz_anthem_q32024',
    canonical_drug_key: 'tocilizumab_iv',
    drug_display_name: 'Tocilizumab IV',
    drug_short_name: 'TCZ',
    biosimilars: ['Tyenne'],
    reference_product: 'Actemra',
    hcpcs_codes: ['J3262', 'Q5127'],
    payer_id: 'anthem',
    payer_name: 'Anthem',
    plan_type: 'Commercial',
    effective_date: '2024-07-01',
    version_label: 'Q3 2024',
    document_hash: 'a5c7e9b1d3f6a0c2',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate', 'one anti-TNF'],
      diagnosis_required: ['Rheumatoid Arthritis', 'GCA', 'sJIA', 'pJIA'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['Lipid panel', 'LFTs', 'CBC'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Labs', 'Specialist notes'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_tcz_anthem_1',
        page: 4,
        section: 'Step Therapy — RA',
        quote: 'Tocilizumab requires failure of methotrexate and at least one anti-TNF. Baseline lipid panel required.',
        source_label: 'Anthem Medical Policy: Tocilizumab (MED.00131)',
        source_url: 'https://www.anthem.com/dam/medpolicies/abcbs/active/policies/mp_pw_d051623.html',
        effective_date: '2024-07-01',
      },
    ],
    friction_score: 67,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_tcz_cigna_q42024',
    canonical_drug_key: 'tocilizumab_iv',
    drug_display_name: 'Tocilizumab IV',
    drug_short_name: 'TCZ',
    biosimilars: ['Tyenne'],
    reference_product: 'Actemra',
    hcpcs_codes: ['J3262', 'Q5127'],
    payer_id: 'cigna',
    payer_name: 'Cigna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'b6d8f0a2c4e7b1d3',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: true,
    clinical_criteria: {
      prior_failure: ['methotrexate', 'one anti-TNF'],
      diagnosis_required: ['Rheumatoid Arthritis', 'GCA'],
      specialty_required: 'Rheumatologist',
      lab_requirements: ['Lipid panel', 'CBC', 'LFTs'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Labs', 'Anti-TNF failure docs'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_tcz_cigna_1',
        page: 3,
        section: 'RA — Step Therapy',
        quote: 'Tocilizumab requires prior inadequate response to methotrexate and anti-TNF therapy.',
        source_label: 'Cigna Coverage Policy: Tocilizumab (MMR1022)',
        source_url: 'https://www.cigna.com/static/www-cigna-com/docs/health-care-professionals/coverage-policies/ph_1022_coveragepositioncriteria_tocilizumab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 60,
    friction_factors: {
      prior_failure_count: 2,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  // ── OCRELIZUMAB ─────────────────────────────────────────────────────────────

  {
    id: 'pol_ocr_aetna_q42024',
    canonical_drug_key: 'ocrelizumab',
    drug_display_name: 'Ocrelizumab',
    drug_short_name: 'OCR',
    biosimilars: [],
    reference_product: 'Ocrevus',
    hcpcs_codes: ['J2350'],
    payer_id: 'aetna',
    payer_name: 'Aetna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'c7e9a1b3d5f8c2e4',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['Relapsing-Remitting MS (RRMS)', 'Primary Progressive MS (PPMS)'],
      specialty_required: 'Neurologist (MS specialist preferred)',
      lab_requirements: ['Hepatitis B screen (HBsAg, anti-HBc)', 'MRI within 12 months'],
      age_restriction: null,
      additional_notes: ['PPMS: baseline EDSS ≤6.5; active lesion or disease progression required.'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: '600 mg IV every 6 months after two 300 mg initial doses (given 2 weeks apart).',
      documentation_required: ['PA form', 'Neurology notes', 'MRI report', 'HBV screen'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ocr_aetna_1',
        page: 3,
        section: '2.1 MS Criteria',
        quote: 'Ocrelizumab is medically necessary for RRMS or PPMS when prescribed by a neurologist with documentation of active disease on MRI. Hepatitis B screening required before initiation.',
        source_label: 'Aetna Clinical Policy Bulletin: Ocrelizumab (CPB #0975)',
        source_url: 'https://www.aetna.com/cpb/medical/data/900_999/0975.html',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 55,
    friction_factors: {
      prior_failure_count: 0,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_ocr_uhc_q42024',
    canonical_drug_key: 'ocrelizumab',
    drug_display_name: 'Ocrelizumab',
    drug_short_name: 'OCR',
    biosimilars: [],
    reference_product: 'Ocrevus',
    hcpcs_codes: ['J2350'],
    payer_id: 'uhc',
    payer_name: 'UnitedHealthcare',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'd8f0b2c4e6a9d1f3',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['RRMS', 'PPMS', 'Active Secondary Progressive MS'],
      specialty_required: 'Neurologist',
      lab_requirements: ['HBV screening'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Neurology notes', 'HBV screen'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ocr_uhc_1',
        page: 2,
        section: 'Authorization Criteria',
        quote: 'Ocrelizumab is covered for RRMS, PPMS, and active SPMS with documentation by a treating neurologist.',
        source_label: 'UHC Medical Drug Policy: Ocrelizumab (D0088)',
        source_url: 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/drug/ocrelizumab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 50,
    friction_factors: {
      prior_failure_count: 0,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_ocr_bsca_q12025',
    canonical_drug_key: 'ocrelizumab',
    drug_display_name: 'Ocrelizumab',
    drug_short_name: 'OCR',
    biosimilars: [],
    reference_product: 'Ocrevus',
    hcpcs_codes: ['J2350'],
    payer_id: 'bsca',
    payer_name: 'Blue Shield CA',
    plan_type: 'Commercial',
    effective_date: '2025-01-01',
    version_label: 'Q1 2025',
    document_hash: 'e9a1c3d5f7b0e2a4',
    coverage_status: 'covered',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['RRMS', 'PPMS'],
      specialty_required: 'Neurologist',
      lab_requirements: ['HBsAg', 'anti-HBc'],
      age_restriction: null,
      additional_notes: ['Streamlined PA for MS specialists on approved panel.'],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 365,
      dosing_notes: null,
      documentation_required: ['PA form', 'Neurology notes', 'HBV labs'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ocr_bsca_1',
        page: 2,
        section: 'Coverage Summary',
        quote: 'Ocrelizumab (Ocrevus) is covered for RRMS and PPMS. Annual renewal. Streamlined authorization available for enrolled MS specialist practices.',
        source_label: 'Blue Shield CA Medical Drug Criteria: Ocrelizumab (Policy CG-MED-201)',
        source_url: 'https://www.blueshieldca.com/bsca/bsc/wcm/connect/provider/provider_content_en/guidelines_resources/medical_drug_criteria/ocrelizumab',
        effective_date: '2025-01-01',
      },
    ],
    friction_score: 28,
    friction_factors: {
      prior_failure_count: 0,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: false,
    },
  },

  {
    id: 'pol_ocr_anthem_q32024',
    canonical_drug_key: 'ocrelizumab',
    drug_display_name: 'Ocrelizumab',
    drug_short_name: 'OCR',
    biosimilars: [],
    reference_product: 'Ocrevus',
    hcpcs_codes: ['J2350'],
    payer_id: 'anthem',
    payer_name: 'Anthem',
    plan_type: 'Commercial',
    effective_date: '2024-07-01',
    version_label: 'Q3 2024',
    document_hash: 'f0b2d4e6a8c1f3b5',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['RRMS', 'PPMS'],
      specialty_required: 'Neurologist',
      lab_requirements: ['HBsAg', 'CBC'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Neurology notes', 'Labs'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ocr_anthem_1',
        page: 3,
        section: 'MS Coverage — Ocrelizumab',
        quote: 'Ocrelizumab is covered for RRMS and PPMS. Neurology documentation required. Renewal every 6 months.',
        source_label: 'Anthem Medical Policy: Ocrelizumab (MED.00144)',
        source_url: 'https://www.anthem.com/dam/medpolicies/abcbs/active/policies/mp_pw_e051624.html',
        effective_date: '2024-07-01',
      },
    ],
    friction_score: 52,
    friction_factors: {
      prior_failure_count: 0,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },

  {
    id: 'pol_ocr_cigna_q42024',
    canonical_drug_key: 'ocrelizumab',
    drug_display_name: 'Ocrelizumab',
    drug_short_name: 'OCR',
    biosimilars: [],
    reference_product: 'Ocrevus',
    hcpcs_codes: ['J2350'],
    payer_id: 'cigna',
    payer_name: 'Cigna',
    plan_type: 'Commercial',
    effective_date: '2024-10-01',
    version_label: 'Q4 2024',
    document_hash: 'a1c3e5b7d9f2a4c6',
    coverage_status: 'conditional',
    pa_required: true,
    step_therapy_required: false,
    clinical_criteria: {
      prior_failure: [],
      diagnosis_required: ['RRMS', 'PPMS'],
      specialty_required: 'Neurologist',
      lab_requirements: ['HBV screen'],
      age_restriction: null,
      additional_notes: [],
    },
    operational_rules: {
      site_of_care: null,
      renewal_interval_days: 180,
      dosing_notes: null,
      documentation_required: ['PA form', 'Neurology notes', 'HBV screen'],
      quantity_limit: null,
    },
    evidence_citations: [
      {
        id: 'cite_ocr_cigna_1',
        page: 2,
        section: 'Coverage Criteria',
        quote: 'Ocrelizumab is covered for RRMS and PPMS with neurologist documentation. Renewal authorization every 6 months.',
        source_label: 'Cigna Coverage Policy: Ocrelizumab (MMR1025)',
        source_url: 'https://www.cigna.com/static/www-cigna-com/docs/health-care-professionals/coverage-policies/ph_1025_coveragepositioncriteria_ocrelizumab.pdf',
        effective_date: '2024-10-01',
      },
    ],
    friction_score: 48,
    friction_factors: {
      prior_failure_count: 0,
      specialist_gate: true,
      lab_biomarker_gate: true,
      site_of_care_restriction: false,
      renewal_complexity: true,
    },
  },
]

// ── Helper: build coverage matrix from MOCK_POLICIES ─────────────────────────

export function buildMockMatrix(): CoverageMatrixData {
  const payer_ids = PAYER_IDS
  const payer_labels = PAYERS

  const rows: MatrixRow[] = DRUG_FAMILIES.map((drug) => {
    const cells: Record<string, MatrixCell> = {}
    for (const payer_id of payer_ids) {
      const policy = MOCK_POLICIES.find(
        (p) => p.canonical_drug_key === drug.key && p.payer_id === payer_id
      )
      cells[payer_id] = policy
        ? {
            policy_id:       policy.id,
            coverage_status: policy.coverage_status,
            friction_score:  policy.friction_score,
            pa_required:     policy.pa_required,
            effective_date:  policy.effective_date,
            version_label:   policy.version_label,
          }
        : {
            policy_id:       null,
            coverage_status: 'unclear',
            friction_score:  0,
            pa_required:     false,
            effective_date:  '',
            version_label:   '',
          }
    }
    return {
      drug_key:          drug.key,
      drug_display_name: drug.display_name,
      drug_short_name:   drug.short_name,
      reference_product: drug.reference_product,
      biosimilars:       drug.biosimilars,
      cells,
    }
  })

  return {
    payer_ids,
    payer_labels,
    rows,
    generated_at: new Date().toISOString(),
  }
}

export function getPolicyById(id: string): PolicyDNA | undefined {
  return MOCK_POLICIES.find((p) => p.id === id)
}

// ── Sample policy diffs for Change Radar ─────────────────────────────────────

export const MOCK_DIFFS: PolicyDiff[] = [
  {
    id: 'diff_ifx_cigna_q3_q4_2024',
    drug_key: 'infliximab',
    drug_display_name: 'Infliximab',
    payer_id: 'cigna',
    payer_name: 'Cigna',
    version_before: 'Q3 2024',
    version_after:  'Q4 2024',
    date_before:    '2024-07-01',
    date_after:     '2024-10-01',
    overall_direction: 'tightened',
    friction_before:   68,
    friction_after:    82,
    friction_delta:    14,
    changes: [
      {
        field:       'step_therapy',
        field_label: 'Step Therapy — Biosimilar-First Requirement',
        change_type: 'tightened',
        before: 'Biosimilar preferred; Remicade requires clinical justification.',
        after:  'Biosimilar MUST be tried and failed before Remicade is covered. Originator covered only with documented biosimilar failure or contraindication.',
        impact: 'high',
        citation_before: null,
        citation_after:  {
          id: 'cite_ifx_cigna_diff_1',
          page: 2,
          section: 'Coverage Conditions — Step Therapy',
          quote: 'Documentation of an adequate trial and failure of an FDA-approved biosimilar infliximab product is required.',
          source_label: 'Cigna Coverage Policy: Infliximab (MMR1005) — Q4 2024',
          source_url: 'https://www.cigna.com/static/www-cigna-com/docs/health-care-professionals/coverage-policies/ph_1005_coveragepositioncriteria_infliximab.pdf',
          effective_date: '2024-10-01',
        },
      },
      {
        field:       'site_of_care',
        field_label: 'Site of Care Restriction',
        change_type: 'tightened',
        before: 'No explicit site restriction.',
        after:  'Restricted to non-hospital settings. Hospital outpatient denied without site-of-care exception.',
        impact: 'high',
        citation_before: null,
        citation_after:  null,
      },
      {
        field:       'prior_failure_count',
        field_label: 'Required Prior Failures',
        change_type: 'tightened',
        before: 'Methotrexate (3 months) required.',
        after:  'Methotrexate (3 months) AND one additional csDMARD required.',
        impact: 'medium',
        citation_before: null,
        citation_after:  null,
      },
    ],
  },
  {
    id: 'diff_vdz_uhc_q3_q4_2024',
    drug_key: 'vedolizumab',
    drug_display_name: 'Vedolizumab',
    payer_id: 'uhc',
    payer_name: 'UnitedHealthcare',
    version_before: 'Q3 2024',
    version_after:  'Q4 2024',
    date_before:    '2024-07-01',
    date_after:     '2024-10-01',
    overall_direction: 'loosened',
    friction_before:   58,
    friction_after:    32,
    friction_delta:    -26,
    changes: [
      {
        field:       'step_therapy',
        field_label: 'Anti-TNF Step Therapy',
        change_type: 'loosened',
        before: 'Prior anti-TNF failure required before vedolizumab.',
        after:  'Anti-TNF step therapy no longer required. Vedolizumab may be used as first biologic after conventional therapy.',
        impact: 'high',
        citation_before: null,
        citation_after:  {
          id: 'cite_vdz_uhc_diff_1',
          page: 2,
          section: 'Authorization Criteria',
          quote: 'Anti-TNF step therapy is not required. Vedolizumab may follow conventional therapy failure.',
          source_label: 'UHC Medical Drug Policy: Vedolizumab (D0072) — Q4 2024',
          source_url: 'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/drug/vedolizumab.pdf',
          effective_date: '2024-10-01',
        },
      },
      {
        field:       'lab_requirements',
        field_label: 'Lab Requirements',
        change_type: 'loosened',
        before: 'TB test, CRP, CBC required.',
        after:  'TB test required; CRP and CBC no longer required at initiation.',
        impact: 'low',
        citation_before: null,
        citation_after:  null,
      },
    ],
  },
  {
    id: 'diff_ocr_bsca_q4_q12025',
    drug_key: 'ocrelizumab',
    drug_display_name: 'Ocrelizumab',
    payer_id: 'bsca',
    payer_name: 'Blue Shield CA',
    version_before: 'Q4 2024',
    version_after:  'Q1 2025',
    date_before:    '2024-10-01',
    date_after:     '2025-01-01',
    overall_direction: 'loosened',
    friction_before:   50,
    friction_after:    28,
    friction_delta:    -22,
    changes: [
      {
        field:       'renewal_interval',
        field_label: 'Renewal Interval',
        change_type: 'loosened',
        before: 'Renewal every 6 months (180 days) with full documentation.',
        after:  'Annual renewal (365 days). Streamlined PA for enrolled MS specialist practices.',
        impact: 'high',
        citation_before: null,
        citation_after:  {
          id: 'cite_ocr_bsca_diff_1',
          page: 2,
          section: 'Coverage Summary',
          quote: 'Annual renewal. Streamlined authorization available for enrolled MS specialist practices.',
          source_label: 'Blue Shield CA Medical Drug Criteria: Ocrelizumab (Policy CG-MED-201) — Q1 2025',
          source_url: 'https://www.blueshieldca.com/bsca/bsc/wcm/connect/provider/provider_content_en/guidelines_resources/medical_drug_criteria/ocrelizumab',
          effective_date: '2025-01-01',
        },
      },
      {
        field:       'specialist_program',
        field_label: 'Specialist Streamlined Program',
        change_type: 'added',
        before: 'Standard PA process for all prescribers.',
        after:  'Enrolled MS specialist practices qualify for streamlined (expedited) PA review.',
        impact: 'medium',
        citation_before: null,
        citation_after:  null,
      },
    ],
  },
]
